### ISSUE TITLE
Duplicated claim "sub" when handling userinfo requests

### ISSUE THREAD

**Issue by z38** [its-dirg/pyop#6]
When handling `userinfo` requests, the "sub" claim is passed twice to `OpenIDSchema`. It seems that `user_claims` contains "sub" as well (because `scope` does contain `openid`).

As a quick workaround I added `user_claims.pop('sub', None)` to [`provider.py`](https://github.com/its-dirg/pyop/blob/4541186/src/pyop/provider.py#L421-L423)

Exception (when used with SATOSA):
```
Traceback (most recent call last):
  File "/var/www/satosa/src/satosa/base.py", line 255, in run
    resp = self._run_bound_endpoint(context, spec)
  File "/var/www/satosa/src/satosa/base.py", line 203, in _run_bound_endpoint
    return spec(context)
  File "/var/www/satosa/src/satosa/frontends/openid_connect.py", line 293, in userinfo_endpoint
    response = self.provider.handle_userinfo_request(urlencode(context.request), headers)
  File "/var/www/satosa/venv/lib/python3.4/site-packages/pyop/provider.py", line 424, in handle_userinfo_request
    response = OpenIDSchema(sub=introspection['sub'], **user_claims)
TypeError: type object got multiple values for keyword argument 'sub'
```

**Comment by rebeckag** [comment]
Thanks for the report!

I can't reproduce this error, and it is probably SATOSA specific.
Could you please open a new issue [there](https://github.com/its-dirg/SATOSA/issues/new) and include your configuration data (`proxy_conf.yaml`, `internal_attributes.yaml`, front-/backend configs without any secrets :))?

**Comment by z38** [comment]
I managed to get a reproducable test case:

```python
from time import time
from pyop.provider import Provider
from pyop.userinfo import Userinfo
from pyop.authz_state import AuthorizationState
from pyop.subject_identifier import HashBasedSubjectIdentifierFactory
from jwkest.jwk import import_rsa_key_from_file

access_token_db = {
    '9614686ae11ccc39a235c27966a767c7': {
        'exp': time() + 60,
        'scope': 'openid',
        'sub': '6336c87ef33d63c18814ea27b351e6c6f091dff5cc922139a20142a3c2e05e50',
        'auth_req': {
            'scope': 'openid',
            'response_type': 'code',
            'client_id': 's6BhdRkqt3',
            'redirect_uri': 'https://client.example.com/login/check'
        }
    }
}
subject_identifier_db = {
    '2e9e3ddb1b9289b80f0ce94904bf819a590d7eeb8bc39e12c6d6a4e118fca3cc88f8e23d015e08': {
        'pairwise': '6336c87ef33d63c18814ea27b351e6c6f091dff5cc922139a20142a3c2e05e50'
    }
}
userinfo_db = {
    '2e9e3ddb1b9289b80f0ce94904bf819a590d7eeb8bc39e12c6d6a4e118fca3cc88f8e23d015e08': {
        'nickname': 'John Doe',
        'sub': '228cd1978c9e6378e046b5e459c0838699b2e4da69f8f5e22c4df4b42f880e88e7c688d8a3319622f0dc13ee7680873f594346aaf2246f103551c9af66461f62',
        'email': 'john@example.com',
        'name': 'John Doe',
        'given_name': 'John',
        'family_name': 'Doe'
    }
}

subject_id_factory = HashBasedSubjectIdentifierFactory('123123')
authz_state = AuthorizationState(subject_id_factory, None, access_token_db, None, subject_identifier_db)
key = import_rsa_key_from_file('key.pem')
config = {
    'issuer': 'https://issuer.example.com',
}

provider = Provider(key, config, authz_state, {}, Userinfo(userinfo_db))
provider.handle_userinfo_request('', {'Authorization': 'Bearer 9614686ae11ccc39a235c27966a767c7'})
```

The contents of `*_db` are copied from our MongoDB instance. Please let me know if you need any further information.

**Comment by rebeckag** [comment]
If this stems from your usage of SATOSA I need the config information for SATOSA to find out how the 'sub' claim ends up in the userinfo_db since that's something I couldn't reproduce with the latest SATOSA version.

Otherwise the simple fix is to remove the 'sub' claim from all user entries in the userinfo_db, since that is computed/issued by `pyop`.
